// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bbk/app/user/internal/dao/internal"
)

// bbkAdminDao is the data access object for the table bbk_admin.
// You can define custom methods on it to extend its functionality as needed.
type bbkAdminDao struct {
	*internal.BbkAdminDao
}

var (
	// BbkAdmin is a globally accessible object for table bbk_admin operations.
	BbkAdmin = bbkAdminDao{internal.NewBbkAdminDao()}
)

// Add your custom methods and functionality below.
