// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bbk/app/user/internal/dao/internal"
)

// bbkUserDao is the data access object for the table bbk_user.
// You can define custom methods on it to extend its functionality as needed.
type bbkUserDao struct {
	*internal.BbkUserDao
}

var (
	// BbkUser is a globally accessible object for table bbk_user operations.
	BbkUser = bbkUserDao{internal.NewBbkUserDao()}
)

// Add your custom methods and functionality below.
