// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin_member

import (
	"bbk/app/geteway/api/admin_member"
)

type ControllerV1 struct{}

func NewV1() admin_member.IAdminMemberV1 {
	return &ControllerV1{}
}
