nacos:
  address: "nacos-grpc.yuanjincheng.cn"
  port: 443
  cacheDir: "E:/www/bbk/tmp/nacos/cache"
  logDir: "E:/www/bbk/tmp/nacos/log"
  username: "nacos"
  password: "nacos"
  namespaceId: "7753e029-aa86-48ec-aa59-d8a15a9c71bc"
  group: "USER_CENTER"
  dataID: "config.yaml"